dubbo:
  registry:
    address: ${zk.url}
    group: /dubbo/test
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
    simplified: true
  #  config-center:
#    address: http://10.255.242.227:8080
#    namespaces: application
#    highest-priority: false
  consumer:
    check: false
    registries:
      - id: r1
        address: ${zk.url}
        group: ${r1.group}
      - id: r2
        address: ${zk.url}
        group: ${r2.group}
    retries: 0
  provider:
    protocols:
      - id: p1
        name: rest
        port: 9111
      - id: p2
        name: dubbo
        port: 9112
